/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCampaignsRouteImport } from './routes/app/campaigns'
import { Route as AppDecisionsRouteImport } from './routes/app/decisions'
import { Route as AppNewPostRouteImport } from './routes/app/new-post'
import { Route as AppPublishedRouteImport } from './routes/app/published'
import { Route as AppScheduledRouteImport } from './routes/app/scheduled'
import { Route as AppSetupRouteImport } from './routes/app/setup'
import { Route as ApiLinkedinCallbackRouteImport } from './routes/api/linkedin/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDecisionsRoute = AppDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNewPostRoute = AppNewPostRouteImport.update({
  id: '/new-post',
  path: '/new-post',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPublishedRoute = AppPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScheduledRoute = AppScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiLinkedinCallbackRoute = ApiLinkedinCallbackRouteImport.update({
  id: '/api/linkedin/callback',
  path: '/api/linkedin/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/new-post': typeof AppNewPostRoute
  '/app/published': typeof AppPublishedRoute
  '/app/scheduled': typeof AppScheduledRoute
  '/app/setup': typeof AppSetupRoute
  '/app/': typeof AppIndexRoute
  '/api/linkedin/callback': typeof ApiLinkedinCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/new-post': typeof AppNewPostRoute
  '/app/published': typeof AppPublishedRoute
  '/app/scheduled': typeof AppScheduledRoute
  '/app/setup': typeof AppSetupRoute
  '/app': typeof AppIndexRoute
  '/api/linkedin/callback': typeof ApiLinkedinCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/decisions': typeof AppDecisionsRoute
  '/app/new-post': typeof AppNewPostRoute
  '/app/published': typeof AppPublishedRoute
  '/app/scheduled': typeof AppScheduledRoute
  '/app/setup': typeof AppSetupRoute
  '/app/': typeof AppIndexRoute
  '/api/linkedin/callback': typeof ApiLinkedinCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/campaigns'
    | '/app/decisions'
    | '/app/new-post'
    | '/app/published'
    | '/app/scheduled'
    | '/app/setup'
    | '/app/'
    | '/api/linkedin/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/campaigns'
    | '/app/decisions'
    | '/app/new-post'
    | '/app/published'
    | '/app/scheduled'
    | '/app/setup'
    | '/app'
    | '/api/linkedin/callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/campaigns'
    | '/app/decisions'
    | '/app/new-post'
    | '/app/published'
    | '/app/scheduled'
    | '/app/setup'
    | '/app/'
    | '/api/linkedin/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiLinkedinCallbackRoute: typeof ApiLinkedinCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/decisions': {
      id: '/app/decisions'
      path: '/decisions'
      fullPath: '/app/decisions'
      preLoaderRoute: typeof AppDecisionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/new-post': {
      id: '/app/new-post'
      path: '/new-post'
      fullPath: '/app/new-post'
      preLoaderRoute: typeof AppNewPostRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/published': {
      id: '/app/published'
      path: '/published'
      fullPath: '/app/published'
      preLoaderRoute: typeof AppPublishedRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/scheduled': {
      id: '/app/scheduled'
      path: '/scheduled'
      fullPath: '/app/scheduled'
      preLoaderRoute: typeof AppScheduledRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/linkedin/callback': {
      id: '/api/linkedin/callback'
      path: '/api/linkedin/callback'
      fullPath: '/api/linkedin/callback'
      preLoaderRoute: typeof ApiLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppDecisionsRoute: typeof AppDecisionsRoute
  AppNewPostRoute: typeof AppNewPostRoute
  AppPublishedRoute: typeof AppPublishedRoute
  AppScheduledRoute: typeof AppScheduledRoute
  AppSetupRoute: typeof AppSetupRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCampaignsRoute: AppCampaignsRoute,
  AppDecisionsRoute: AppDecisionsRoute,
  AppNewPostRoute: AppNewPostRoute,
  AppPublishedRoute: AppPublishedRoute,
  AppScheduledRoute: AppScheduledRoute,
  AppSetupRoute: AppSetupRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiLinkedinCallbackRoute: ApiLinkedinCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
